captainVersion: 4
caproverOneClickApp:
  displayName: FireCrawl
  isOfficial: false
  description: A distributed web crawling and scraping system with AI-powered content extraction capabilities.
  instructions:
    start: |-
      FireCrawl is a powerful web crawling system that combines:
      - Distributed crawling with Redis-backed queues
      - Playwright-based browser automation
      - AI-powered content extraction
      - Rate limiting and proxy support
      - Real-time notifications
    end: |-
      FireCrawl has been successfully deployed! 

      Important next steps:
      1. Configure your environment variables, especially:
         - OpenAI API key for content extraction
         - Proxy settings if needed
         - Authentication details if enabled
      2. The API will be available at http://$$cap_appname.$$cap_root_domain
      3. Make sure to set up your webhook URLs for notifications if needed
  variables:
    - id: $$cap_port
      label: API Port
      defaultValue: "3000"
      description: Port number for the API service
      validRegex: /^[0-9]+$/
    - id: $$cap_proxy_server
      label: Proxy Server URL
      description: Full URL of the proxy server (optional)
    - id: $$cap_proxy_username
      label: Proxy Authentication Username
      description: Username for proxy authentication (optional)
    - id: $$cap_proxy_password
      label: Proxy Authentication Password
      description: Password for proxy authentication (optional)
    - id: $$cap_block_media
      label: Block Media Resources
      defaultValue: "false"
      description: Whether to block loading media resources like images and videos
      validRegex: /^(true|false)$/
    - id: $$cap_use_db_authentication
      label: Enable Database Authentication
      defaultValue: "false"
      description: Whether to use database authentication
      validRegex: /^(true|false)$/
    - id: $$cap_num_workers_per_queue
      label: Workers Per Queue
      defaultValue: "8"
      description: Number of worker processes per queue
      validRegex: /^[0-9]+$/
    - id: $$cap_openai_api_key
      label: OpenAI API Key
      description: API key for OpenAI services
    - id: $$cap_openai_base_url
      label: OpenAI API Base URL
      defaultValue: "https://api.openai.com/v1"
      description: Base URL for OpenAI API (for custom endpoints)
    - id: $$cap_model_name
      label: OpenAI Model Name
      defaultValue: "gpt-4o-mini"
      description: Name of the OpenAI model to use
    - id: $$cap_slack_webhook_url
      label: Slack Webhook URL
      description: Webhook URL for Slack notifications
    - id: $$cap_llamaparse_api_key
      label: LlamaParse API Key
      description: API key for LlamaParse service
    - id: $$cap_logtail_key
      label: Logtail Source Token
      description: Source token for Logtail logging
    - id: $$cap_bull_auth_key
      label: Bull Queue Auth Key
      description: Authentication key for Bull queue dashboard
    - id: $$cap_test_api_key
      label: Test API Key
      defaultValue: $$cap_gen_random_hex(32)
      description: API key for testing purposes
    - id: $$cap_posthog_api_key
      label: PostHog Project API Key
      description: API key for PostHog analytics
    - id: $$cap_posthog_host
      label: PostHog Host URL
      description: Host URL for PostHog instance
    - id: $$cap_supabase_anon_token
      label: Supabase Anon Key
      description: Anonymous API key for Supabase
    - id: $$cap_supabase_url
      label: Supabase Project URL
      description: URL of your Supabase project
    - id: $$cap_supabase_service_token
      label: Supabase Service Role Key
      description: Service role API key for Supabase
    - id: $$cap_scraping_bee_api_key
      label: ScrapingBee API Key
      description: API key for ScrapingBee service
    - id: $$cap_host
      label: Application Host
      defaultValue: "localhost"
      description: Host address to bind the application to
    - id: $$cap_self_hosted_webhook_url
      label: Self-Hosted Webhook URL
      description: Webhook URL for self-hosted notifications
    - id: $$cap_logging_level
      label: Logging Level
      defaultValue: "info"
      description: Application logging level (debug, info, warn, error)
    - id: $$cap_fly_process_group
      label: Fly.io Process Group
      description: Process group identifier for Fly.io deployment
    - id: $$cap_redis_version
      label: Redis Version
      defaultValue: "alpine"
      description: Redis Docker image version tag
services:
  $$cap_appname-playwright-service:
    image: nullmastermind/firecrawl-playwright-service:latest
    environment:
      PORT: "3000"
      PROXY_SERVER: $$cap_proxy_server
      PROXY_USERNAME: $$cap_proxy_username
      PROXY_PASSWORD: $$cap_proxy_password
      BLOCK_MEDIA: $$cap_block_media
    caproverExtra:
      notExposeAsWebApp: true
  $$cap_appname-api:
    image: nullmastermind/firecrawl-api:latest
    environment:
      REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379
      REDIS_RATE_LIMIT_URL: redis://srv-captain--$$cap_appname-redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://srv-captain--$$cap_appname-playwright-service:3000
      USE_DB_AUTHENTICATION: $$cap_use_db_authentication
      PORT: $$cap_port
      NUM_WORKERS_PER_QUEUE: $$cap_num_workers_per_queue
      OPENAI_API_KEY: $$cap_openai_api_key
      OPENAI_BASE_URL: $$cap_openai_base_url
      MODEL_NAME: $$cap_model_name
      SLACK_WEBHOOK_URL: $$cap_slack_webhook_url
      LLAMAPARSE_API_KEY: $$cap_llamaparse_api_key
      LOGTAIL_KEY: $$cap_logtail_key
      BULL_AUTH_KEY: $$cap_bull_auth_key
      TEST_API_KEY: $$cap_test_api_key
      POSTHOG_API_KEY: $$cap_posthog_api_key
      POSTHOG_HOST: $$cap_posthog_host
      SUPABASE_ANON_TOKEN: $$cap_supabase_anon_token
      SUPABASE_URL: $$cap_supabase_url
      SUPABASE_SERVICE_TOKEN: $$cap_supabase_service_token
      SCRAPING_BEE_API_KEY: $$cap_scraping_bee_api_key
      HOST: $$cap_host
      SELF_HOSTED_WEBHOOK_URL: $$cap_self_hosted_webhook_url
      LOGGING_LEVEL: $$cap_logging_level
      FLY_PROCESS_GROUP: app
    command:
      - pnpm
      - run
      - start:production
    caproverExtra:
      containerHttpPort: "3002"
    depends_on:
      - $$cap_appname-redis
      - $$cap_appname-playwright-service
  $$cap_appname-worker:
    image: nullmastermind/firecrawl-worker:latest
    environment:
      REDIS_URL: redis://srv-captain--$$cap_appname-redis:6379
      REDIS_RATE_LIMIT_URL: redis://srv-captain--$$cap_appname-redis:6379
      PLAYWRIGHT_MICROSERVICE_URL: http://srv-captain--$$cap_appname-playwright-service:3000
      USE_DB_AUTHENTICATION: $$cap_use_db_authentication
      PORT: $$cap_port
      NUM_WORKERS_PER_QUEUE: $$cap_num_workers_per_queue
      OPENAI_API_KEY: $$cap_openai_api_key
      OPENAI_BASE_URL: $$cap_openai_base_url
      MODEL_NAME: $$cap_model_name
      SLACK_WEBHOOK_URL: $$cap_slack_webhook_url
      LLAMAPARSE_API_KEY: $$cap_llamaparse_api_key
      LOGTAIL_KEY: $$cap_logtail_key
      BULL_AUTH_KEY: $$cap_bull_auth_key
      TEST_API_KEY: $$cap_test_api_key
      POSTHOG_API_KEY: $$cap_posthog_api_key
      POSTHOG_HOST: $$cap_posthog_host
      SUPABASE_ANON_TOKEN: $$cap_supabase_anon_token
      SUPABASE_URL: $$cap_supabase_url
      SUPABASE_SERVICE_TOKEN: $$cap_supabase_service_token
      SCRAPING_BEE_API_KEY: $$cap_scraping_bee_api_key
      HOST: $$cap_host
      SELF_HOSTED_WEBHOOK_URL: $$cap_self_hosted_webhook_url
      LOGGING_LEVEL: $$cap_logging_level
      FLY_PROCESS_GROUP: worker
    command:
      - pnpm
      - run
      - workers
    caproverExtra:
      notExposeAsWebApp: true
    depends_on:
      - $$cap_appname-redis
      - $$cap_appname-playwright-service
      - $$cap_appname-api
  $$cap_appname-redis:
    image: redis:$$cap_redis_version
    command: redis-server
    caproverExtra:
      notExposeAsWebApp: true
