captainVersion: 4
caproverOneClickApp:
  instructions:
    start: Just a plain Docker Compose.
    end: Docker Compose is deployed.
  variables:
    - id: $$cap_langflowai_langflow_version
      label: Version | Langflow
      defaultValue: latest
      description: Check the tag version on https://hub.docker.com/r/langflowai/langflow
      validRegex: /^[\w.-]+$/ # Allow alphanumeric, dots and dashes
    - id: $$cap_postgres_version
      label: Version | PostgreSQL
      defaultValue: "16"
      validRegex: /^[\d.]+$/ # Only numbers and dots
    - id: $$cap_postgres_user
      label: PostgreSQL | User
      defaultValue: langflow
    - id: $$cap_postgres_password
      label: PostgreSQL | Password
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: /^.{8,}$/
    - id: $$cap_postgres_db
      label: PostgreSQL | Database
      defaultValue: langflow
services:
  $$cap_appname-langflow:
    image: langflowai/langflow:$$cap_langflowai_langflow_version
    environment:
      LANGFLOW_DATABASE_URL: postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--$$cap_appname-postgres:5432/$$cap_postgres_db
      LANGFLOW_CONFIG_DIR: /app/langflow
    volumes:
      - $$cap_appname-langflow-data:/app/langflow
    caproverExtra:
      containerHttpPort: "7860"
    depends_on:
      - $$cap_appname-postgres
  $$cap_appname-postgres:
    image: postgres:$$cap_postgres_version
    environment:
      POSTGRES_USER: $$cap_postgres_user
      POSTGRES_PASSWORD: $$cap_postgres_password
      POSTGRES_DB: $$cap_postgres_db
    volumes:
      - $$cap_appname-langflow-postgres:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: true
