captainVersion: 4
caproverOneClickApp:
  instructions:
    start: |-
      Langflow is a UI for LangChain, designed with react-flow to provide an effortless way 
      to experiment and prototype flows with drag-and-drop components. This deployment uses
      the official Langflow Docker image with PostgreSQL backend.
    end: |-
      Langflow has been deployed! It might take a few moments to initialize.

      Access your instance at: $$cap_appname.$$cap_root_domain

      Default credentials: admin / admin (change immediately in settings)
  displayName: Langflow
  isOfficial: false
  description: A UI for LangChain enabling visual prototyping of LLM workflows with drag-and-drop components.
  documentation: https://github.com/langflow-ai/langflow
  variables:
    - id: $$cap_langflowai_langflow_version
      label: Version | Langflow
      defaultValue: latest
      description: Check the tag version on https://hub.docker.com/r/langflowai/langflow
    - id: $$cap_postgres_version
      label: Version | PostgreSQL
      defaultValue: "16"
    - id: $$cap_postgres_user
      label: PostgreSQL | User
      defaultValue: langflow
    - id: $$cap_postgres_password
      label: PostgreSQL | Password
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: /^.{8,}$/
    - id: $$cap_postgres_db
      label: PostgreSQL | Database
      defaultValue: langflow
    - id: $$cap_langflow_secret_key
      label: Langflow Secret Key
      defaultValue: $$cap_gen_random_hex(32)
      description: Secret key used for security tokens and encryption
    - id: $$cap_langflow_superuser
      label: Admin Username
      defaultValue: admin
      description: Initial administrator username
    - id: $$cap_langflow_superuser_password
      label: Admin Password
      defaultValue: $$cap_gen_random_hex(16)
      validRegex: /^.{8,}$/
      description: Initial administrator password (min 8 characters)
services:
  $$cap_appname:
    image: langflowai/langflow:$$cap_langflowai_langflow_version
    environment:
      LANGFLOW_DATABASE_URL: postgresql://$$cap_postgres_user:$$cap_postgres_password@srv-captain--$$cap_appname-postgres:5432/$$cap_postgres_db
      LANGFLOW_CONFIG_DIR: app/langflow
      LANGFLOW_AUTO_LOGIN: False
      LANGFLOW_SUPERUSER: $$cap_langflow_superuser
      LANGFLOW_SUPERUSER_PASSWORD: $$cap_langflow_superuser_password
      LANGFLOW_SECRET_KEY: $$cap_langflow_secret_key
      LANGFLOW_NEW_USER_IS_ACTIVE: True
    volumes:
      - $$cap_appname-langflow-data:/app/langflow
    caproverExtra:
      containerHttpPort: "7860"
  $$cap_appname-postgres:
    image: postgres:$$cap_postgres_version
    environment:
      POSTGRES_USER: $$cap_postgres_user
      POSTGRES_PASSWORD: $$cap_postgres_password
      POSTGRES_DB: $$cap_postgres_db
    volumes:
      - $$cap_appname-langflow-postgres:/var/lib/postgresql/data
    caproverExtra:
      notExposeAsWebApp: true
